services:
  app:
    container_name: monitor_pro
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
